name: 'Pull Request: Content'

on:
  pull_request:
    types: [edited, opened]

jobs:
  validation_title:
    name: 'Validation: Title'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: '🛎 Checkout'
        uses: actions/checkout@v4
      - name: '🦫 Setup Golang'
        uses: ./.github/actions/use-go-dependencies
      - name: '✅ Validate'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "${PR_TITLE}" | commitlint lint
